# Generated by Django 4.1.5 on 2023-02-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App1', '0002_delete_curso_delete_entregable_delete_estudiantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recCarne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechaDeSubida', models.DateField()),
                ('ingredientes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recPastas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechaDeSubida', models.DateField()),
                ('ingredientes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recVerduras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechaDeSubida', models.DateField()),
                ('ingredientes', models.TextField()),
            ],
        ),
    ]
