# Generated by Django 4.1.5 on 2023-02-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
