# Generated by Django 4.1.5 on 2023-02-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reccarne',
            name='ingredientes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recpastas',
            name='ingredientes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recverduras',
            name='ingredientes',
            field=models.CharField(max_length=200),
        ),
    ]
