# Generated by Django 4.1.5 on 2023-02-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_alter_reccarne_ingredientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombre',
            new_name='nombreC',
        ),
        migrations.RenameField(
            model_name='reccarne',
            old_name='nombre',
            new_name='nombreC',
        ),
        migrations.RenameField(
            model_name='recpastas',
            old_name='nombre',
            new_name='nombreP',
        ),
        migrations.RenameField(
            model_name='recverduras',
            old_name='nombre',
            new_name='nombreV',
        ),
    ]
