# Generated by Django 4.1.5 on 2023-02-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_rename_nombre_contacto_nombrec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombreC',
            new_name='nombreCo',
        ),
        migrations.RenameField(
            model_name='reccarne',
            old_name='nombreC',
            new_name='nombreCa',
        ),
    ]
