# Generated by Django 4.1.5 on 2023-02-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_rename_nombrec_contacto_nombreco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombreCo',
            new_name='nombre',
        ),
    ]
