# Generated by Django 4.1.5 on 2023-02-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_rename_nombreco_contacto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reccarne',
            old_name='nombreCa',
            new_name='nombre',
        ),
    ]
