# Generated by Django 4.1.5 on 2023-02-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_rename_nombreca_reccarne_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recpastas',
            old_name='nombreP',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='recverduras',
            old_name='nombreV',
            new_name='nombre',
        ),
    ]
